#!/usr/bin/env bash
# Install or refresh macOS launchd job for JobFinderOS (single master scheduler).
# Usage: bash scripts/JobFinderOS_install_launchd.sh
#
# Launch entry script is written to ~/.jobfinderos/ so launchd can execute it
# (scripts under ~/Documents are often blocked with "Operation not permitted").
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export ROOT
RUNTIME="${JOBFINDEROS_RUNTIME:-codex}"
case "$RUNTIME" in codex|claude) ;; *) echo "Unsupported runtime: $RUNTIME" >&2; exit 2 ;; esac
printf -v RUNTIME_Q '%q' "$RUNTIME"
printf -v CODEX_BIN_Q '%q' "${CODEX_BIN:-$(command -v codex || true)}"
printf -v CLAUDE_BIN_Q '%q' "${CLAUDE_BIN:-$(command -v claude || true)}"
AGENT_DIR="${HOME}/Library/LaunchAgents"
LAUNCHER_DIR="${HOME}/.jobfinderos"
SCHEDULER_LABEL="com.jobfinderos.scheduler"

DAILY_HOUR="${JOBS_DAILY_HOUR:-7}"
DAILY_MINUTE="${JOBS_DAILY_MINUTE:-0}"
WEEKLY_HOUR="${MARK_WEEKLY_HOUR:-8}"
WEEKLY_MINUTE="${MARK_WEEKLY_MINUTE:-0}"
# launchd: 0 = Sunday, 1 = Monday, …, 6 = Saturday
WEEKDAY="${MARK_WEEKLY_WEEKDAY:-1}"
SCHEDULER_INTERVAL_SECONDS="${SCHEDULER_INTERVAL_SECONDS:-1800}"
WATCH_HOUR="${WATCH_HOUR:-9}"
WATCH_MINUTE="${WATCH_MINUTE:-0}"

mkdir -p "$AGENT_DIR"
mkdir -p "$ROOT/logs"
mkdir -p "$ROOT/config"
mkdir -p "$LAUNCHER_DIR"
chmod +x "$ROOT/scripts/JobFinderOS_run_agent.sh" "$ROOT/scripts/JobFinderOS_run_skill.sh" \
  "$ROOT/scripts/JobFinderOS_run_daily.sh" "$ROOT/scripts/JobFinderOS_run_weekly.sh" \
  "$ROOT/scripts/JobFinderOS_test_launchd.sh" "$ROOT/scripts/JobFinderOS_log_run.sh" \
  "$ROOT/scripts/jobfinderos_priority_watch.py" \
  "$ROOT/scripts/jobfinderos_daily_guard.py" "$ROOT/scripts/jobfinderos_weekly_guard.py" \
  2>/dev/null || true

cat >"$ROOT/config/scheduler.yaml" <<EOF
# JobFinderOS master scheduler — due windows (local timezone).
# Regenerated by scripts/JobFinderOS_install_launchd.sh (env: JOBS_DAILY_*, MARK_WEEKLY_*, SCHEDULER_INTERVAL_SECONDS).
#
# Watch job (invoked each scheduler tick; guard enforces watch.hour on weekdays):
#   jobfinderos_priority_watch.py → /jobs-priority-watch

start_interval_seconds: ${SCHEDULER_INTERVAL_SECONDS}

# IANA timezone for all windows (empty = system local time)
timezone: "${JOBFINDEROS_TZ:-}"

daily:
  hour: ${DAILY_HOUR}
  minute: ${DAILY_MINUTE}

weekly:
  weekday: ${WEEKDAY}
  hour: ${WEEKLY_HOUR}
  minute: ${WEEKLY_MINUTE}

watch:
  hour: ${WATCH_HOUR}
  minute: ${WATCH_MINUTE}
EOF

SCHEDULER_LAUNCHER="${LAUNCHER_DIR}/JobFinderOS_launchd_scheduler.sh"

cat >"$SCHEDULER_LAUNCHER" <<EOF
#!/usr/bin/env bash
set -euo pipefail
ROOT="${ROOT}"
export JOBFINDEROS_RUNTIME=${RUNTIME_Q}
export CODEX_BIN=${CODEX_BIN_Q}
export CLAUDE_BIN=${CLAUDE_BIN_Q}
export PATH="\$ROOT/.venv/bin:\$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:\$PATH"
cd "\$ROOT"
mkdir -p "\$ROOT/logs"
"\$ROOT/.venv/bin/python" "\$ROOT/scripts/scheduler_tick.py"
EOF

chmod +x "$SCHEDULER_LAUNCHER"

WORK_DIR="${HOME}"

write_plist_interval() {
  local outfile="$1"
  local label="$2"
  local interval="$3"
  local program="$4"

  cat >"$outfile" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${label}</string>
  <key>WorkingDirectory</key>
  <string>${WORK_DIR}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${program}</string>
  </array>
  <key>StartInterval</key>
  <integer>${interval}</integer>
  <key>StandardOutPath</key>
  <string>${ROOT}/logs/launchd-${label}.log</string>
  <key>StandardErrorPath</key>
  <string>${ROOT}/logs/launchd-${label}.err</string>
  <key>ProcessType</key>
  <string>Background</string>
</dict>
</plist>
EOF
}

SCHEDULER_PLIST="${AGENT_DIR}/${SCHEDULER_LABEL}.plist"
LEGACY_DAILY="${AGENT_DIR}/com.jobfinderos.jobs-daily.plist"
LEGACY_WEEKLY="${AGENT_DIR}/com.jobfinderos.mark-weekly.plist"

UID_VAL="$(id -u)"
DOMAIN="gui/${UID_VAL}"

# Legacy two-job install → remove
launchctl bootout "$DOMAIN" "$LEGACY_DAILY" 2>/dev/null || true
launchctl bootout "$DOMAIN" "$LEGACY_WEEKLY" 2>/dev/null || true
rm -f "$LEGACY_DAILY" "$LEGACY_WEEKLY" 2>/dev/null || true

launchctl bootout "$DOMAIN" "$SCHEDULER_PLIST" 2>/dev/null || true

write_plist_interval "$SCHEDULER_PLIST" "$SCHEDULER_LABEL" "$SCHEDULER_INTERVAL_SECONDS" "$SCHEDULER_LAUNCHER"

launchctl bootstrap "$DOMAIN" "$SCHEDULER_PLIST"
launchctl enable "$DOMAIN/${SCHEDULER_LABEL}"

INSTALL_TS="$(date '+%Y-%m-%d %H:%M %Z')"
export INSTALL_TS DAILY_HOUR DAILY_MINUTE WEEKLY_HOUR WEEKLY_MINUTE WEEKDAY SCHEDULER_INTERVAL_SECONDS
python3 <<'PY'
import os
from pathlib import Path

root = Path(os.environ["ROOT"])
note = root / "vault" / "Automation" / "JobFinderOS — Schedule & Run Log.md"
dh, dm = os.environ["DAILY_HOUR"], os.environ["DAILY_MINUTE"]
wh, wm = os.environ["WEEKLY_HOUR"], os.environ["WEEKLY_MINUTE"]
wd = os.environ["WEEKDAY"]
interval = os.environ["SCHEDULER_INTERVAL_SECONDS"]
ts = os.environ["INSTALL_TS"]
launcher = str(Path.home() / ".jobfinderos")
dhm = f"{dh}:{str(dm).zfill(2)}"
whm = f"{wh}:{str(wm).zfill(2)}"
im = str(int(interval) // 60)
scheduler_label = "com.jobfinderos.scheduler"

header = f"""> **JobFinderOS:** system · {ts}

# JobFinderOS automation

macOS **launchd** (user session). One **master** agent runs `scripts/scheduler_tick.py` every **{interval}s** (~{im} min) while the Mac is awake; the tick reads [[config/scheduler.yaml]] and `~/.jobfinderos/scheduler_state.json`, runs canonical agent tasks when due (Codex by default), and invokes the priority-function watch guard each tick. Re-run `scripts/JobFinderOS_install_launchd.sh` to refresh.

## Scheduled jobs (logical)

| Job | After (local) | Entrypoint |
|-----|----------------|------------|
| Daily Jobs | Every day after **{dhm}** | `scheduler_tick` → `JobFinderOS_run_agent.sh coach jobs-daily` |
| Weekly Mark | Weekday **{wd}** (0=Sun … 1=Mon) after **{whm}** | `scheduler_tick` → `JobFinderOS_run_agent.sh mark mark-weekly` |
| Priority watch | Weekdays after the watch time in `config/scheduler.yaml` | `jobfinderos_priority_watch.py` → `/jobs-priority-watch` |

**Rule — weekly wins:** If the weekly job runs on a calendar day, the daily job is skipped that day.

## launchd

| Label | Mechanism | Program |
|-------|-----------|---------|
| `{scheduler_label}` | `StartInterval` **{interval}s** | `{launcher}/JobFinderOS_launchd_scheduler.sh` |

Plist: `~/Library/LaunchAgents/{scheduler_label}.plist`
"""
note.parent.mkdir(parents=True, exist_ok=True)
if note.exists():
    t = note.read_text(encoding="utf-8")
    if "## Run log" in t:
        tail = t.split("## Run log", 1)[1]
        body = header.strip() + "\n\n## Run log" + tail
    else:
        body = header.strip() + (
            "\n\n## Run log\n\n"
            "Each scheduled run appends **start** / **completed** / **failed** lines to "
            "`logs/launchd-runs.log` in the project root (gitignored). The same lines are mirrored "
            "below when macOS allows background jobs to write here (if this section stays empty, "
            "open `logs/launchd-runs.log` on disk).\n\n"
            "_Newest entries at the bottom._\n\n"
        )
else:
    body = header.strip() + (
        "\n\n## Run log\n\n"
        "Each scheduled run appends **start** / **completed** / **failed** lines to "
        "`logs/launchd-runs.log` in the project root (gitignored). The same lines are mirrored "
        "below when macOS allows background jobs to write here (if this section stays empty, "
        "open `logs/launchd-runs.log` on disk).\n\n"
        "_Newest entries at the bottom._\n\n"
    )
note.write_text(body, encoding="utf-8")
PY

echo "Installed:"
echo "  Config: ${ROOT}/config/scheduler.yaml"
echo "  Launcher: ${SCHEDULER_LAUNCHER}"
echo "  ${SCHEDULER_LABEL} — StartInterval ${SCHEDULER_INTERVAL_SECONDS}s (~$((SCHEDULER_INTERVAL_SECONDS / 60)) min)"
echo "Logs: ${ROOT}/logs/launchd-${SCHEDULER_LABEL}.log / .err"
echo "Run events (start/completed/failed): ${ROOT}/logs/launchd-runs.log"
echo "State: ~/.jobfinderos/scheduler_state.json"
echo "Schedule note: vault/Automation/JobFinderOS — Schedule & Run Log.md"
echo ""
echo "Optional env overrides: JOBS_DAILY_HOUR JOBS_DAILY_MINUTE MARK_WEEKLY_HOUR MARK_WEEKLY_MINUTE MARK_WEEKLY_WEEKDAY WATCH_HOUR WATCH_MINUTE SCHEDULER_INTERVAL_SECONDS JOBFINDEROS_TZ"
echo "Dry-run tick: ${ROOT}/.venv/bin/python ${ROOT}/scripts/scheduler_tick.py --dry-run"
echo "Quick test: bash ${ROOT}/scripts/JobFinderOS_test_launchd.sh"
echo ""

case "$ROOT" in
  *"/Documents/"*|*"/Desktop/"*|*"/Downloads/"*)
    echo "----------------------------------------------------------------"
    echo "NOTE: Project is under a TCC-protected folder (Documents/Desktop/Downloads)."
    echo "If launchd still fails, either:"
    echo "  1) Move the repo (e.g. to ~/Developer/JobFinderOS) and re-run this script, OR"
    echo "  2) System Settings → Privacy & Security → Full Disk Access → add:"
    echo "       ${ROOT}/.venv/bin/python"
    echo "----------------------------------------------------------------"
    ;;
esac
